#!/bin/sh
# lintian-local.sh — run lintian against a locally-built package
# using the same invocation as CI, so "passes on the laptop" and
# "passes in CI" cannot diverge.
#
# Usage: from the top of the duckdb git tree, after running
# `dpkg-buildpackage -us -uc -b`:
#
#     debian/scripts/lintian-local.sh
#
# Exit code is propagated from lintian; a clean run exits 0.
#
# The shared invocation is also used by
# .github/workflows/debian-package.yml — keep the two in sync.
# If you add a --suppress-tags entry here, also document the
# justification in this file's header comment so future-you can
# tell why each was suppressed.
#
# ------------------------------------------------------------------
# Suppressed tags (each one needs a justification):
#
#   orig-tarball-missing-upstream-signature
#       Snapshot builds use a +git<date>.<hash> version with no
#       upstream signature.  Released tagged builds will not need
#       this suppression.
#
#   bad-distribution-in-changes-file
#       debian/changelog distribution is UNRELEASED on snapshot
#       builds.  Tagged release uploads set this to e.g. trixie or
#       unstable.
#
#   source-is-missing  source-contains-prebuilt-javascript-object
#       DuckDB vendors third-party code under third_party/ with its
#       own licensing already documented via the delegating
#       "Files: third_party/*" stanza in debian/copyright.
#
#   very-long-line-length-in-source-file
#       The amalgamation header duckdb.hpp (~5 MB) is generated by
#       upstream's CMake, not by us.
#
#   embedded-library
#       libduckdb1 statically embeds the in-tree extensions listed
#       in debian/rules' DUCKDB_EXTENSIONS by design.  They are not
#       separately installable Debian packages.
#
#   bugs-field-does-not-refer-to-debian-infrastructure
#       The Bugs: field points at https://github.com/mjgajda/duckdb/issues
#       on purpose -- this packaging fork lives outside Debian BTS and
#       wants reports to land where the packaging maintainer can act on
#       them.  See debian/control's comment above the Bugs: line.  If
#       this package is ever uploaded to Debian proper, the field is
#       changed to bugs.debian.org and this suppression removed.
#
#   initial-upload-closes-no-bugs
#       debian/changelog has only one entry and no Closes: #NNN because
#       this packaging never went through Debian's ITP process (the
#       upload destination is github.com/mjgajda/duckdb and the OBS
#       PPA, not bugs.debian.org).  When/if we file an ITP for Debian
#       proper, the entry will reference it and this suppression goes
#       away.

set -eu

SUPPRESS_TAGS='orig-tarball-missing-upstream-signature,bad-distribution-in-changes-file,source-is-missing,source-contains-prebuilt-javascript-object,very-long-line-length-in-source-file,embedded-library,bugs-field-does-not-refer-to-debian-infrastructure,initial-upload-closes-no-bugs'

# Find a .changes file to lint.  Two common locations:
#   ../             — default of dpkg-buildpackage
#   artefacts/      — staging dir used by the CI workflow
changes_files=
for d in .. artefacts; do
    for f in "$d"/*.changes; do
        [ -f "$f" ] && changes_files="$changes_files $f"
    done
done
changes_files=$(printf '%s' "$changes_files" | sed 's/^ //')

if [ -z "$changes_files" ]; then
    printf 'lintian-local.sh: no .changes file found in ../ or artefacts/.\n' >&2
    printf 'Run `dpkg-buildpackage -us -uc -b` first.\n' >&2
    exit 2
fi

# --fail-on error,warning gates CI on the strict severity floor.
# --info / --display-info surface every finding so suppression
# decisions can be re-evaluated later.
# shellcheck disable=SC2086
exec lintian \
    --fail-on error,warning \
    --info \
    --display-info \
    --suppress-tags "$SUPPRESS_TAGS" \
    $changes_files
